"""Run a single dev-process node execution (1 exec = 1 logical session = 1 evidence).

P10: every Codex exec in the main path flows through ``run_node_exec``.

``model`` resolved from ``exec_policy_snapshot`` is recorded in both ``NodeRun``
and the evidence JSON as **audit metadata**.  It is *not* injected into worker argv
yet; model selection remains the responsibility of the argv preset.  A future phase
(P10.5 / P11) may add argv-level model injection per worker type.

``session_id`` is a **logical** identifier deterministically derived from
``(run_id, node_name, index)``.  Provider-level session isolation (e.g. Codex
session resume) is worker-dependent and not guaranteed by ``run_node_exec`` itself.
"""

from __future__ import annotations

import hashlib
import os
import subprocess
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from nodeflow.core.base_node import NodeExecutionFailure
from nodeflow.workflows.dev_process.argv_builder import resolve_node_exec
from nodeflow.workflows.dev_process.constants import EXEC_TIMEOUT_SECONDS
from nodeflow.workflows.dev_process.constraints import (
    format_constraints_for_prompt,
    generate_node_agents_md,
    resolve_constraints,
)
from nodeflow.workflows.dev_process.evidence import record_exec_evidence
from nodeflow.workflows.dev_process.node_run import NODE_TYPE_PREFIX, NodeRun
from nodeflow.workflows.dev_process.session_store import new_session_id
from nodeflow.workflows.dev_process.workers import resolve_exec_worker, run_exec

# Constraints that trigger hard validation
_READ_ONLY_CONSTRAINT = "READ_ONLY_NODE"
_NO_TOUCH_EXISTING_UNTRACKED = "NO_TOUCH_EXISTING_UNTRACKED"

_NODEFLOW_PATH_PREFIXES = (".nodeflow/", " .nodeflow/")

_CODEX_HOME_AGENTS_HEADER = """\
# Dev-process task instructions

These instructions are generated by dev-process for this specific node execution.

If these instructions conflict with repository-local AGENTS.md files,
the dev-process constraints in this file and in the current prompt take precedence
for this automated run.

---

"""


def _default_codex_home() -> Path:
    """Return the default CODEX_HOME directory (where ``codex login`` stores auth)."""
    env_home = os.environ.get("CODEX_HOME")
    if env_home:
        return Path(env_home).expanduser()
    return Path.home() / ".codex"


_CODEX_AUTH_FILES = ("auth.json", "config.toml")


def _link_codex_auth(target_dir: Path) -> None:
    """Symlink auth-related files from the default CODEX_HOME into *target_dir*.

    Without this, overriding ``CODEX_HOME`` for per-node AGENTS.md delivery
    causes Codex to lose access to ``codex login`` credentials (→ 401).

    Raises ``NodeExecutionFailure`` when a symlink cannot be created —
    copying ``auth.json`` into the artifact tree would leak credentials.
    """
    src_dir = _default_codex_home()
    for name in _CODEX_AUTH_FILES:
        src = src_dir / name
        dst = target_dir / name
        if src.is_file() and not dst.exists() and not dst.is_symlink():
            try:
                dst.symlink_to(src)
            except OSError as exc:
                raise NodeExecutionFailure(
                    f"failed to symlink Codex auth file into per-node CODEX_HOME: {name}"
                ) from exc


def _write_node_codex_home(
    *,
    artifact_root: str,
    node_name: str,
    constraint_ids: List[str],
    snapshot: Dict[str, Any],
) -> Tuple[str, str]:
    """Generate per-node CODEX_HOME/AGENTS.md with only this node's effective constraints.

    Also symlinks auth files from the real CODEX_HOME so that the
    overridden ``CODEX_HOME`` still has valid credentials.

    Returns (codex_home_dir, agents_md_sha256).
    """
    content = generate_node_agents_md(constraint_ids, snapshot)
    full_content = _CODEX_HOME_AGENTS_HEADER + content
    sha = hashlib.sha256(full_content.encode("utf-8")).hexdigest()

    codex_home_dir = Path(artifact_root) / "codex_home" / node_name
    codex_home_dir.mkdir(parents=True, exist_ok=True)
    agents_path = codex_home_dir / "AGENTS.md"
    agents_path.write_text(full_content, encoding="utf-8")
    _link_codex_auth(codex_home_dir)
    return str(codex_home_dir), sha


def _git(cwd: str, args: List[str]) -> str:
    """Run a git command and return stripped stdout (empty on error)."""
    try:
        cp = subprocess.run(
            ["git", *args],
            cwd=cwd,
            capture_output=True,
            text=True,
            check=False,
            timeout=10,
        )
        return cp.stdout.strip() if cp.returncode == 0 else ""
    except (OSError, subprocess.TimeoutExpired):
        return ""


def _filter_nodeflow_lines(status: str) -> str:
    """Remove .nodeflow/ entries from git status output."""
    return "\n".join(
        line
        for line in status.splitlines()
        if not any(line.lstrip().startswith(p) or p in line for p in _NODEFLOW_PATH_PREFIXES)
    )


def _git_readonly_fingerprint(cwd: str) -> str:
    """Capture full repo state for READ_ONLY_NODE check.

    Includes HEAD, branch, porcelain status, and sha256 of working-tree diff
    and staged diff. This detects content changes even when the file was already
    dirty before execution (git status alone would show 'M' in both cases).
    """
    head = _git(cwd, ["rev-parse", "HEAD"])
    branch = _git(cwd, ["rev-parse", "--abbrev-ref", "HEAD"])
    status = _filter_nodeflow_lines(_git(cwd, ["status", "--porcelain"]))

    diff_worktree = _git(cwd, ["diff", "--", ":(exclude).nodeflow"])
    diff_staged = _git(cwd, ["diff", "--cached", "--", ":(exclude).nodeflow"])
    diff_hash = hashlib.sha256(diff_worktree.encode("utf-8")).hexdigest()
    staged_hash = hashlib.sha256(diff_staged.encode("utf-8")).hexdigest()

    return (
        f"HEAD={head}\nBRANCH={branch}\nSTATUS=\n{status}\n"
        f"DIFF_HASH={diff_hash}\nSTAGED_HASH={staged_hash}"
    )


def _collect_untracked_checksums(cwd: str) -> Dict[str, str]:
    """Collect sha256 of existing untracked files (excluding .nodeflow/).

    Uses git ls-files --others for file-level enumeration (handles directories).
    """
    import hashlib
    import os

    raw = _git(cwd, ["ls-files", "--others", "--exclude-standard", "-z"])
    untracked: Dict[str, str] = {}
    for path in raw.split("\0"):
        if not path or path.startswith(".nodeflow/"):
            continue
        full = os.path.join(cwd, path)
        if os.path.isfile(full):
            try:
                with open(full, "rb") as f:
                    untracked[path] = hashlib.sha256(f.read()).hexdigest()
            except OSError:
                pass
    return untracked


def _validate_post_constraints(
    constraint_ids: List[str],
    cwd: str,
    pre_fingerprint: str,
    pre_untracked: Dict[str, str],
) -> Dict[str, Any]:
    """Hard validation: check constraints that can be verified mechanically.

    Returns a validation result dict:
      {"ok": True, "constraints": [...]} on success
      {"ok": False, "violated": "...", "message": "...", "constraints": [...]} on failure

    Does NOT raise; caller is responsible for writing the artifact and raising.
    """
    import os

    if _READ_ONLY_CONSTRAINT in constraint_ids:
        post_fingerprint = _git_readonly_fingerprint(cwd)
        if post_fingerprint != pre_fingerprint:
            return {
                "ok": False,
                "violated": _READ_ONLY_CONSTRAINT,
                "message": (
                    f"repository state changed during execution.\n"
                    f"Before:\n{pre_fingerprint[:300]}\nAfter:\n{post_fingerprint[:300]}"
                ),
                "constraints": constraint_ids,
            }
        if pre_untracked:
            for path, expected_hash in pre_untracked.items():
                full = os.path.join(cwd, path)
                if not os.path.exists(full):
                    return {
                        "ok": False,
                        "violated": _READ_ONLY_CONSTRAINT,
                        "message": f"untracked file deleted: {path}",
                        "constraints": constraint_ids,
                    }
                if os.path.isfile(full):
                    with open(full, "rb") as f:
                        current_hash = hashlib.sha256(f.read()).hexdigest()
                    if current_hash != expected_hash:
                        return {
                            "ok": False,
                            "violated": _READ_ONLY_CONSTRAINT,
                            "message": f"untracked file modified: {path}",
                            "constraints": constraint_ids,
                        }

    if _NO_TOUCH_EXISTING_UNTRACKED in constraint_ids and pre_untracked:
        post_untracked_paths = set(
            p
            for p in _git(cwd, ["ls-files", "--others", "--exclude-standard", "-z"]).split("\0")
            if p
        )

        for path, expected_hash in pre_untracked.items():
            full = os.path.join(cwd, path)
            if not os.path.exists(full):
                return {
                    "ok": False,
                    "violated": _NO_TOUCH_EXISTING_UNTRACKED,
                    "message": f"previously untracked file deleted: {path}",
                    "constraints": constraint_ids,
                }
            if path not in post_untracked_paths:
                return {
                    "ok": False,
                    "violated": _NO_TOUCH_EXISTING_UNTRACKED,
                    "message": f"previously untracked file was staged or committed: {path}",
                    "constraints": constraint_ids,
                }
            if os.path.isfile(full):
                with open(full, "rb") as f:
                    current_hash = hashlib.sha256(f.read()).hexdigest()
                if current_hash != expected_hash:
                    return {
                        "ok": False,
                        "violated": _NO_TOUCH_EXISTING_UNTRACKED,
                        "message": f"previously untracked file modified: {path}",
                        "constraints": constraint_ids,
                    }

    return {"ok": True, "constraints": constraint_ids}


def _write_validation_artifact(
    artifact_root: str,
    node_name: str,
    validation_result: Dict[str, Any],
) -> str:
    """Write constraint validation result as a JSON artifact."""
    import json
    from datetime import datetime, timezone

    validation_result["node_name"] = node_name
    validation_result["validated_at"] = datetime.now(timezone.utc).isoformat()

    val_dir = Path(artifact_root) / "evidence" / "constraint_validations"
    val_dir.mkdir(parents=True, exist_ok=True)
    path = val_dir / f"{node_name}_validation.json"
    path.write_text(json.dumps(validation_result, indent=2), encoding="utf-8")
    return str(path)


def _build_merged_env(extra: Optional[Dict[str, str]]) -> Optional[Dict[str, str]]:
    """Replicate the env merging that ``CodexExecNode._resolve_env`` performs.

    Returns ``None`` (inherit parent env) when *extra* is empty.
    """
    if not extra:
        return None
    merged = dict(os.environ)
    merged.update({str(k): str(v) for k, v in extra.items()})
    return merged


def _preflight_worker_auth(
    argv: List[str],
    *,
    cwd: str,
    env: Optional[Dict[str, str]],
) -> None:
    """Verify Codex auth works with the same cwd/env the real exec will use.

    Runs a minimal ``codex exec --sandbox read-only`` (or skips when *argv*
    is not a recognisable codex invocation or the binary is missing).
    Raises ``NodeExecutionFailure`` on auth / connectivity failure.
    """
    import shutil

    import click as _click

    if len(argv) < 2:
        return
    codex_bin = argv[0]
    is_codex = codex_bin.endswith("codex") and argv[1] == "exec"
    is_npx = codex_bin == "npx" and len(argv) >= 3 and argv[1] == "codex" and argv[2] == "exec"
    if not is_codex and not is_npx:
        return

    _click.echo(">> Codex auth preflight...", err=True)
    resolved_env = _build_merged_env(env)
    check_path = resolved_env.get("PATH", "") if resolved_env else os.environ.get("PATH", "")
    if not shutil.which(codex_bin, path=check_path if resolved_env else None):
        return

    if is_codex:
        cmd = [codex_bin, "exec", "--sandbox", "read-only", "Reply with OK only."]
    else:
        cmd = ["npx", "codex", "exec", "--sandbox", "read-only", "Reply with OK only."]

    try:
        proc = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=60,
            check=False,
            cwd=cwd,
            env=resolved_env,
        )
    except subprocess.TimeoutExpired:
        raise NodeExecutionFailure("codex worker preflight timed out (60 s). Check network / auth.")
    if proc.returncode != 0:
        stderr_tail = (proc.stderr or "").strip()[-500:]
        raise NodeExecutionFailure(
            f"codex worker preflight failed (exit {proc.returncode}). "
            f"The worker env may lack valid credentials.\n{stderr_tail}"
        )


def append_node_run_record(body: Dict[str, Any], record: NodeRun) -> None:
    """Append a ``NodeRun`` to ``body[\"node_runs\"]``."""
    body.setdefault("node_runs", []).append(record.to_dict())


def _write_skipped_evidence(
    *,
    artifact_root: str,
    node_name: str,
    skip_reason: str,
) -> str:
    """Write a minimal skipped-node evidence JSON for audit."""
    import json

    ev_dir = Path(artifact_root) / "evidence" / "skipped"
    ev_dir.mkdir(parents=True, exist_ok=True)
    ev_path = ev_dir / f"{node_name}.json"
    ev_path.write_text(
        json.dumps(
            {
                "node_name": node_name,
                "kind": "skipped",
                "skip_reason": skip_reason,
            },
            indent=2,
        ),
        encoding="utf-8",
    )
    return str(ev_path)


def record_skipped_node_run(
    body: Dict[str, Any],
    *,
    node_name: str,
    stage: str,
    skip_reason: str,
    evidence_path: str = "",
    artifact_root: Optional[str] = None,
) -> NodeRun:
    """Record a skipped leaf node attempt (no worker exec)."""
    ev_path = evidence_path
    if not ev_path and artifact_root:
        ev_path = _write_skipped_evidence(
            artifact_root=artifact_root,
            node_name=node_name,
            skip_reason=skip_reason,
        )
    record = NodeRun(
        node_name=node_name,
        node_type=f"{NODE_TYPE_PREFIX}.{node_name}",
        stage=stage,
        kind="skipped",
        worker="local",
        model=None,
        session_id=None,
        evidence_path=ev_path,
        argv=[],
        skipped=True,
        skip_reason=skip_reason,
    )
    append_node_run_record(body, record)
    return record


def record_local_node_run(
    body: Dict[str, Any],
    *,
    node_name: str,
    stage: str,
    evidence_path: str,
    argv: Optional[List[str]] = None,
    kind: str = "local",
) -> NodeRun:
    """Record a local (non-LLM) leaf node execution."""
    record = NodeRun(
        node_name=node_name,
        node_type=f"{NODE_TYPE_PREFIX}.{node_name}",
        stage=stage,
        kind=kind,
        worker="local",
        model=None,
        session_id=None,
        evidence_path=evidence_path,
        argv=list(argv or []),
        skipped=False,
    )
    append_node_run_record(body, record)
    return record


def review_argv_override_from_body(body: Dict[str, Any]) -> Optional[List[str]]:
    """Optional per-review argv override (e.g. force-blocking integration tests)."""
    dp = body.get("dev_process") if isinstance(body.get("dev_process"), dict) else {}
    raw = dp.get("review_argv_override")
    if raw is None:
        return None
    if not isinstance(raw, list) or not all(isinstance(x, str) for x in raw):
        raise NodeExecutionFailure("dev_process.review_argv_override must be a list of strings")
    return list(raw)


def clear_review_argv_override(body: Dict[str, Any]) -> None:
    """Remove scoped review argv override so it does not leak across review segments."""
    dp = body.get("dev_process")
    if isinstance(dp, dict):
        dp.pop("review_argv_override", None)


def run_node_exec(
    body: Dict[str, Any],
    *,
    node_name: str,
    stage: str,
    prompt: str,
    cwd: str,
    run_id: str,
    artifact_root: str,
    invoker_override: Optional[str] = None,
    argv_override: Optional[List[str]] = None,
    timeout: int = EXEC_TIMEOUT_SECONDS,
) -> Tuple[Dict[str, Any], str, NodeRun]:
    """Execute one node and record it in ``body["node_runs"]``.

    *argv_override*, when given, replaces the argv resolved from
    ``exec_policy_snapshot`` (e.g. ``dev_process.review_argv_override`` on body).

    Returns ``(execution_output, evidence_path, record)``.
    """
    worker_kind, model, argv = resolve_node_exec(body, node_name)
    if argv_override is not None:
        argv = list(argv_override)
    worker = resolve_exec_worker(worker_kind)

    dp = body.get("dev_process") if isinstance(body.get("dev_process"), dict) else {}
    snapshot = (
        dp.get("exec_policy_snapshot") if isinstance(dp.get("exec_policy_snapshot"), dict) else {}
    )
    constraint_ids = resolve_constraints(snapshot, node_name)
    if constraint_ids:
        constraints_text = format_constraints_for_prompt(constraint_ids, snapshot)
        prompt = f"{prompt}\n\n{constraints_text}"

    needs_validation = bool(constraint_ids)
    pre_fingerprint = _git_readonly_fingerprint(cwd) if needs_validation else ""
    needs_untracked_check = needs_validation and (
        _NO_TOUCH_EXISTING_UNTRACKED in constraint_ids or _READ_ONLY_CONSTRAINT in constraint_ids
    )
    pre_untracked = _collect_untracked_checksums(cwd) if needs_untracked_check else {}

    codex_home: Optional[str] = None
    agents_md_sha256: Optional[str] = None
    exec_env: Optional[Dict[str, str]] = None
    if constraint_ids:
        codex_home, agents_md_sha256 = _write_node_codex_home(
            artifact_root=artifact_root,
            node_name=node_name,
            constraint_ids=constraint_ids,
            snapshot=snapshot,
        )
        exec_env = {"CODEX_HOME": codex_home}

    _preflight_worker_auth(argv, cwd=cwd, env=exec_env)

    node_runs = body.setdefault("node_runs", [])
    session_id = new_session_id(run_id=run_id, node_name=node_name, index=len(node_runs))
    execution_output = run_exec(
        worker, prompt=prompt, cwd=cwd, argv=argv, timeout=timeout, env=exec_env
    )

    invoker = invoker_override or worker.invoker
    evidence_path = record_exec_evidence(
        artifact_root=artifact_root,
        run_id=run_id,
        stage=stage,
        invoker=invoker,
        execution_output=execution_output,
        argv=argv,
        prompt=prompt,
        cwd=cwd,
        node_name=node_name,
        session_id=session_id,
        model=model,
        worker=worker_kind,
        constraints=constraint_ids,
        codex_home=codex_home,
        agents_md_sha256=agents_md_sha256,
    )
    record = NodeRun(
        node_name=node_name,
        node_type=f"{NODE_TYPE_PREFIX}.{node_name}",
        stage=stage,
        kind="llm",
        worker=worker_kind,
        model=model,
        session_id=session_id,
        evidence_path=evidence_path,
        argv=argv,
        constraints=constraint_ids,
    )
    append_node_run_record(body, record)

    if needs_validation:
        validation_result = _validate_post_constraints(
            constraint_ids, cwd, pre_fingerprint, pre_untracked
        )
        _write_validation_artifact(artifact_root, node_name, validation_result)
        if not validation_result["ok"]:
            raise NodeExecutionFailure(
                f"{validation_result['violated']} violation: {validation_result['message']}"
            )

    return execution_output, evidence_path, record
